included:
  - Sources
disabled_rules:
  - line_length
  - identifier_name
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - trailing_comma
  - todo
  # alineación en columnas de las tablas de rutas/objetivos
  - comma
  # usamos tuplas de 3 con nombres en escáneres internos
  - large_tuple
  - statement_position
  - implicit_optional_initialization
